services:
{{if .WithAvalanchego}}
  avalanchego:
    image: avaplatform/avalanchego:{{ .AvalanchegoVersion }}
{{if .E2E }}
    container_name: avalanchego{{.E2ESuffix}}
{{ else }}
    container_name: avalanchego
{{ end }}
    restart: unless-stopped
    user: "1000:1000"  # ubuntu user
    command: >
        ./avalanchego
        --config-file=/.avalanchego/configs/node.json
{{if .E2E }}
    volumes:
      avalancego_data_{{.E2ESuffix}}:/.avalanchego:rw
      avalancego_logs_{{.E2ESuffix}}:/.avalanchego/logs:rw
    ports:
      - "{{ .E2EIP }}:9650:9650"
      - "{{ .E2EIP }}:9651:9651"
    networks:
      - avalanchego_net_{{.E2ESuffix}}
{{ else }}
    volumes:
      - /home/ubuntu/.avalanchego:/.avalanchego:rw
    ports:
      - "9650:9650"
      - "9651:9651"
    networks:
      - avalanchego_net
{{ end }}
{{ end }}
{{if .WithMonitoring}}
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    user: "0:999"  # root user docker group
    command: -config.file=/etc/promtail/promtail.yml
{{if .E2E }}
    volumes:
      - avalancego_logs_{{.E2ESuffix}}:/.avalanchego/logs:rw
      - /home/ubuntu/.avalanche-cli/services/promtail:/etc/promtail:ro
    networks:
      - avalanchego_net_{{.E2ESuffix}}
{{ else }}
    volumes:
      - /home/ubuntu/.avalanchego/logs:/logs:ro
      - /home/ubuntu/.avalanche-cli/services/promtail:/etc/promtail:ro
    networks:
      - avalanchego_net
{{ end }}
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
{{if .WithAvalanchego}}
    links:
      - avalanchego
{{end}}
{{if .E2E }}
    networks:
      - avalanchego_net_{{.E2ESuffix}}
{{ else }}
    networks:
      - avalanchego_net
{{ end }}
{{ end }}

{{if .E2E }}
volumes:
  avalancego_data_{{.E2ESuffix}}:
  avalancego_logs_{{.E2ESuffix}}:
networks:
  avalanchego_net_{{.E2ESuffix}}:
{{ else }}
networks:
  avalanchego_net:
{{ end }}
    