---
- hosts: "{{ target }}"
  tasks:
    - name: get Avalanche Go Version
      uri:
        url: http://127.0.0.1:9650/ext/info
        method: POST
        body: "{\"jsonrpc\":\"2.0\", \"id\":1,\"method\" :\"info.getNodeVersion\"}"
        body_format: json
        return_content: yes
        headers:
          Content-Type: "application/json"
      register: command_output
    - copy:
        dest: "{{ avalancheGoJsonPath }}"
        content: "{{ command_output[\"content\"] | from_json | to_nice_json }}"
      delegate_to: localhost