---
- hosts: "{{ target }}"
  tasks:
    - name: install gcc
      shell: |
        gcc --version && exit
        sudo apt install gcc -y
        gcc --version
    - name: install go
      shell: |
        bash -i -c "go version" && exit
        GOFILE=go{{ goVersion }}.linux-amd64.tar.gz
        cd ~
        sudo rm -rf $GOFILE go
        wget -nv https://go.dev/dl/$GOFILE
        tar xfz $GOFILE
        echo >> ~/.bashrc
        echo export PATH=\$PATH:~/go/bin >> ~/.bashrc
        echo export CGO_ENABLED=1 >> ~/.bashrc
        bash -i -c "go version"
    - name: install rust
      shell: |
        bash -i -c "cargo version" && exit
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s - -y
        echo >> ~/.bashrc
        echo export PATH=\$PATH:~/.cargo/bin >> ~/.bashrc
        bash -i -c "cargo version"
